language: python
python: 3.5
env:
  matrix:
   - TOXENV=py27
   - TOXENV=pypy
   - TOXENV=py33
   - TOXENV=py34
   - TOXENV=py35
   - TOXENV=flake8
install:
  - pip install tox
  - if test "$TOXENV" = py34 ; then pip install coveralls ; fi
script: tox
after_script:
  - if test "$TOXENV" = py34 ; then coveralls ; fi
